- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
> fix: Set CameraPositionState.position when using .move()

- .github/workflows/test.yml
Disable testing on `gh-pages` branch.
> ci: Ignore gh-pages branch for test workflow.

- README.md
- app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt
Clarify in the README that `CameraPositionState` and `MapProperties` should be used for anything that recomposes the map. Conversely, `GoogleMapOptions` should only be used for initializing the map (properties that can only be provided in map initialization like map ID).
The documentation page in https://developers.google.com/maps/documentation/android-sdk/maps-compose#add_a_map_to_your_app will also be updated shortly.
Fixes #42 🦕
> chore: Fix recommendation on setting the camera's position.

- .github/workflows/instrumentation-test.yml
- .github/workflows/test.yml
- app/build.gradle
- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt
- build.gradle
Add tests for CameraPositionState. Need to make some changes in the `test.yml` workflow still so that these tests are invoked on each PR and pushes.
Fixes #23 🦕
> chore(Test): Add UI tests

- README.md
Clarify in the README that `MapUiSettings` should be preferred for configuring UI-related properties of the map. `GoogleMapOptions` should only be used for one-time configurations (map ID, lite mode enabling, etc.).
Fixes #58 🦕
> docs(README): Clarify that MapUiSettings should be preferred.

- README.md
Link to releases page to help find the required version of Jetpack Compose for a given library version. The appropriate release notes have been updated to mention when the version of Jetpack Compose was bumped.
Fixes #64 🦕
> docs: Link releases for required version of Compose.

- app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt
- build.gradle
Support snapshots and also bumps version to `2.0.0-SNAPSHOT`.
Fixes #60 🦕
> chore: Support snapshot releases

- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapApplier.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
Support showing/hiding info window on the marker's state object. This PR also renames `MarkerPositionState` to the more generic name `MarkerState`.
Fixes #16, closes #33  🦕
> feat: Support showing/hiding info window.

- README.md
- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/MapSampleActivity.kt
- build.gradle
- maps-compose/src/main/java/com/google/maps/android/compose/MapApplier.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
Merging 2.0 related changes into `main`. Marker (and siblings) now requires passing in a `MarkerState` to set its position and control its info window.
Changes:
* Enables observing marker drag events (#11)
* Enables showing/hiding info window (#69)
Closes #16
> chore: Maps Compose 2.0.0

- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
> feat: Support specifying animation duration for camera changes.

- app/build.gradle
Adds the `maps_android_compose_dependency` region tag.
> chore: Add maps_android_compose_dependency region tag.

- README.md
Users are installing older version of Compose and hitting problems - see:
* https://github.com/googlemaps/android-maps-compose/issues/67#issuecomment-1107847164
* https://discordapp.com/channels/676948200904589322/939194796138975263/966366331492524102
This change makes it clearer in the installation instructions what the current base Compose requirement is without needing to look through the release notes.
---
> docs: Add compose version requirement to installation

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
Someone on Discord asked about setting the padding on the `GoogleMap`, and I realized that we're missing Javadocs for this parameter.
This PR adds the missing Javadocs, based on:
https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/GoogleMap#setPadding(int,%20int,%20int,%20int)
---
> docs: Add missing Javadocs for GoogleMap contentPadding parameter

- README.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/java/com/google/maps/android/compose/MapClusteringActivity.kt
- app/src/main/java/com/google/maps/android/compose/MapInColumnActivity.kt
- app/src/main/res/values/strings.xml
- maps-compose/build.gradle
- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapEffect.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapsComposeExperimentalApi.kt
Create `MapEffect` composable to expose the underlying `GoogleMap` Maps SDK object to enable extension and usages such as clustering with the utility library.
Example:
```kotlin
@OptIn(MapsComposeExperimentalApi::class)
@Composable
fun GoogleMapClustering(items: List<MyItem>) {
val cameraPositionState = rememberCameraPositionState {
position = CameraPosition.fromLatLngZoom(singapore, 10f)
}
GoogleMap(
modifier = Modifier.fillMaxSize(),
cameraPositionState = cameraPositionState
) {
val context = LocalContext.current
var clusterManager by remember { mutableStateOf<ClusterManager<MyItem>?>(null) }
MapEffect(items) { map ->
clusterManager = ClusterManager<MyItem>(context, map)
clusterManager?.addItems(items)
}
LaunchedEffect(key1 = cameraPositionState.isMoving) {
if …
```
> feat: Add experimental MapEffect composable

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/maps/android/compose/LocationTrackingActivity.kt
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/res/values/strings.xml
This PR adds a new activity to the demo app to show how to use `LocationSource` and enable the "My location" layer. This allows you to move the blue "my location" dot around on the screen based on your own `Location` objects.
This implementation generates fake locations randomly every 2 seconds and updates the blue dot and animates the map camera accordingly:
We can also use this activity to demo the feature for the source of camera movement (https://github.com/googlemaps/android-maps-compose/issues/49) when that is implemented.
---
> docs: Add LocationTrackingActivity to example app

- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/LocationTrackingActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/CameraMoveStartedReason.kt
- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
As discussed in https://github.com/googlemaps/android-maps-compose/issues/49, this PR exposes the `reason` value passed back in `GoogleMap.OnCameraMoveStartedListener(int reason)` callback so that developers can tell the reason that the camera started moving (e.g., user gesture, developer animation, API animation):
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveStartedListener#onCameraMoveStarted(int)
For constant values see:
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveStartedListener#constants
The PR also adds demo code to `LocationTrackingActivity` to print the reason that the camera moves, as well as assertions to test behavior in an existing unit test.
---
Before submitting your …
> feat: Add the reason for map camera movement

- app/src/main/res/values/strings.xml
This PR normalizes the names of the demo app Activities by removing the word "Activity" from two of them to match the others that do not have "Activity".
Here's the new home screen look:
---
> chore: Normalize demo app Activity names

- app/src/main/java/com/google/maps/android/compose/ScaleBarActivity.kt
- maps-compose-widgets/src/main/java/com/google/maps/android/compose/widgets/ScaleBar.kt
This PR fixes the modifier (e.g., for alignment) for the DisappearingScaleBar by passing it into the `AnimatedVisibility` instead of `ScaleBar`.
Also tweaks/fixes the demo app padding.
---
Fixes https://github.com/googlemaps/android-maps-compose/issues/165 🦕
> fix: DisappearingScaleBar modifier (e.g., for alignment)

- maps-compose-widgets/src/main/java/com/google/maps/android/compose/widgets/ScaleBar.kt
Addresses a fix for #166 where DisappearingScaleBar does not disappear after specified visibilityDurationMillis. I think it's good to remove the condition so that the visibility and delay will restart every time the zoom changes. This will make sure that after given visibilityDurationMillis the ScaleBar will disappear. Also, any zoom change will restart the LaunchedEffect again so that the old time-out will not be an issue.
I would love to hear the feedback if this is the correct way to address the issue or not. Any comments will be valuable.
Fixes #166
> fix: DisappearingScaleBar do not disappear after specified visibilityDurationMillis

- app/build.gradle
- build.gradle
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
- maps-compose/src/main/java/com/google/maps/android/compose/Polygon.kt
Compose now supports independent versioning: https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html
* Updates compose compiler to the stable version (1.2.0)
* Updates compose libraries to the latest 1.2.0 rc (1.2.0-rc03)
* Updates target/compile SDK to 32
> chore: Update Compose libraries and Compiler.

- .github/workflows/instrumentation-test.yml
- .github/workflows/test.yml
Use pull_request_target so that PRs from forked repos have access to secrets. This should fix failed runs due to the Maps API key not being injected: https://github.com/googlemaps/android-maps-compose/runs/7283340731
Relates to https://github.com/googlemaps/android-maps-compose/issues/174 🦕
Same as #175 but opening this PR from a branch.
> chore: Use pull_request_target.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Android Studio Chipmunk suggests bumping the Gradle and AGP versions. I did this hoping it would help with the flaky CI test in https://github.com/googlemaps/android-maps-compose/issues/174, but alas it does not. Tests pass locally.
**EDIT** - Per my comment at https://github.com/googlemaps/android-maps-compose/pull/180#discussion_r922545699, this might be one piece of the puzzle towards fixing https://github.com/googlemaps/android-maps-compose/issues/174.
---
> chore: Bump Gradle and AGP

- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
- settings.gradle
First of all, thanks for an awesome project! 🤩 I really like it!
In this PR I have tried to implement version catalog for dependency management.  This is important to ensure consistency in library versions across modules.
~~There are some things to consider. The AGP version is not yet updated (7.0.4) and therefore [version catalog]~~
~~(https://docs.gradle.org/current/userguide/platforms.html) is still experimental.  However, since there was a PR on~~ 
~~this ([181](https://github.com/googlemaps/android-maps-compose/pull/181)) I thought this was okay. Then I can~~
~~rebase and remove the `enableFeaturePreview` flag when that is merged. Furthermore, I have not~~
~~implemented `plugins` in `library.versions.toml` as that is a feature that was added in version 7.2 of gradle.~~
Update: …
> feat: Use version catalog for dependency management

- .github/workflows/instrumentation-test.yml
- .github/workflows/test.yml
- app/src/androidTest/java/com/google/maps/android/compose/MapInColumnTests.kt
Disables flaky test on CI.
I decided to disable it since commits have been landing to `main` despite the test failing. It's a known env-specific issue and  I think disabling this is the right move so that merges aren't accidentally made when a different failure happens. This should be uncommented again and addressed as part of https://github.com/googlemaps/android-maps-compose/issues/174.
> chore: Disable flaky test.

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
This PR fixes a memory leak that can happen in AndroidView when navigating to another screen.
The Lifecycle ON_DESTROY event is never called because in onDispose we remove the mapLifecycleObserver and this method is called before the Lifecycle ON_DESTROY event.
We have to handle any Lifecycle ON_DESTROY in the onDispose method.
---
Fixes #138 🦕
> fix: Prevent a memory leak on AndroidView which may not call ON_DESTROY

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
> fix: `GoogleMap` in preview early return breaking preview layout

- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
> chore: Use BOM for Compose deps and bump compiler to 1.3.2

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
#206 introduced a crash when disposing the MapView, as reported in #207. Since the `DisposableEffect` has multiple keys, changes to any of them will result in the MapView becoming destroyed, which is not necessarily what we want. [This repro project](https://github.com/thekingrenz23/GoogleMapsBottomNav) (extremely helpful, thank you @thekingrenz23!) revealed a case where the lifecycle owner (one of the DisposableEffect keys) can change without changing the MapView or context. This puts the MapView into a bad state, where it's "destroyed" but still shown and fully interactible.
This moves the MapView disposal into its own DisposableEffect with _only_ the MapView as a key, avoiding the unwanted disposal.
Fixes #207 🦕
> fix: Separate MapView disposal from LifecycleOwner changes

- .github/workflows/instrumentation-test.yml
Follow-up to https://github.com/googlemaps/.github/pull/57
> chore: Use new Maps API secret in instrumentation tests

- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/androidTest/java/com/google/maps/android/compose/MapInColumnTests.kt
- app/src/androidTest/java/com/google/maps/android/compose/TestUtils.kt
Currently when no API key is provided, the instrumentation tests fail with a cryptic "Map loaded" exception. This adds a more explicit error when no API key is provided.
> chore: Fail tests when API key is missing

- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
`CameraPositionState` has a few unstable properties. Rather than verify all usages of these are safe for stability, I'm opting to back them with mutable states, so the compiler can mark the class stable for us.
`MarkerState`'s `internal var: Marker?` property was causing the class to be marked unstable.
While I think it can safely be marked `@Stable` as-is, I'd rather have the compiler infer that. I feel better backing it with an actual state value, that way if we later do an actual non-imperative state read it won't break stuff.
Verified stability via compiler report.
Fixes #232 🦕
> perf: Make CameraPositionState and MarkerState stable

- settings.gradle
We're on a version of Gradle that has version catalogs enabled by default, so this flag isn't needed anymore.
> chore: Remove no-longer-needed Version Catalogs feature flag

- README.md
- build.gradle
This removes most of the custom setup of the Maven publication in favor of [AGP's components](https://developer.android.com/studio/publish-library).
Some notable changes:
- Before, the generated POM did not contain any dependencies. The old code suggests it might, but since it only adds dependencies from the `api` configuration, of which `:maps-compose` has none, the actual `<dependencies/>` block in the POM was empty.
With this change, the POM has expected dependencies, e.g. `play-services-maps`.
- Gradle Module metadata is now present in the publication. To my knowledge, this shouldn't result in any noticeable changes for users, as we aren't shipping test fixtures.
Generated Javadoc jar still contains Dokka stuff.
> fix: Migrate publication to AGP's publishing API

- gradle/libs.versions.toml
This fixes instrumentation tests on API 33, as reported in [b/240993946](https://issuetracker.google.com/issues/240993946).
> chore: Upgrade AndroidX Test to 1.5.0

- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
As mentioned in https://github.com/googlemaps/android-maps-compose/pull/258#discussion_r1088385067, this makes the map's `CameraPositionState` globally accessible via a ~`CompositionLocal`~ public Composable property. Since the camera position state is global across the map, this should be safe to expose publicly. This is useful for components that are dependent on the camera state, such as Clustering ~and `ScaleBar`~.
Actually, since `ScaleBar` is a UI composable and not a Map composable, that doesn't work.
> feat: Add public currentCameraPositionState property

- maps-compose/src/main/java/com/google/maps/android/compose/ComposeInfoWindowAdapter.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapApplier.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapComposeViewRender.kt
The Maps library relies on rendering Views to bitmaps in order to populate some UI. I know of two use cases for that: Marker info windows (already implemented), and custom Cluster icons. This attempts to make the solution reusable, albeit hacky, by refactoring that functionality into some utility functions.
> chore: Add internal utility for rendering a ComposeView

- gradle.properties
This disables Jetifier in the build. Jetifier is a compatibility tool that transforms pre-AndroidX libraries to make them use their AndroidX counterparts. Since this project has no pre-AndroidX libraries, it's not needed, so we can disable it as recommended by Android Studio's build analyzer.
> chore: Disable Jetifier

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/Clustering.kt
This observes `items` via `snapshotFlow`, which fixes the case in #269 where a single `MutableStateList` of items is passed.
Fixes #269 🦕
> fix: Fix Clustering not updating when new items are provided

- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
As pointed out in #277, we don't need the Parcelize plugin, as we don't have any `@Parcelized` types.
Closes #277
> chore: Remove Parcelize plugin

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt
This fixes a crash when rendering custom cluster content. It seems to be timing-related. T cluster renderer creates markers that aren't actually meant to be rendered, so we don't have an active ComposeView for it. This works around it by simply no-op'ing when that happens.
Fixes #271 🦕
> fix: Fix NoSuchElementException when rendering custom cluster content

- .github/workflows/instrumentation-test.yml
This PR fixes a problem we were having with the env variable for MAPS_API_KEY ON GitHub. We are switching the order of the assignment, and then if the key is empty we assign a default value.
> fix: fixed issue with CI/CD in the instrumentation tests

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt
This PR prevents a crash when the Bitmap size is zero in the ClusterRenderer.
`measuredWidth` and `measuredHeight` typically return 0 when we call them from `onCreate`, which does not seem to be the case. This is also not deterministic and not always reproducible. For some reason, the view has not been drawn when we hit this point.
This PR will prevent the crash, although the causes need to be determined.
Fixes #297
> fix: fixed crash when the Bitmap size is zero in the ClusterRenderer

- gradle/libs.versions.toml
This PR updates Google Maps SDK to 18.1.0
18.1.0 introduces advanced polylines: https://developers.google.com/maps/documentation/android-sdk/release-notes
---
Fixes #337
> chore: updated Google Maps SDK to 18.1.0

- README.md
The example given crashes (#265). Changed location to match BasicMapActivity.kt, which works.
> chore(docs): fix Street View location in README

- README.md
This PR makes a small improvement to the readme documentation, showing a fuller example on how to use `ScaleBar` and `DisappearingScaleBar`.
I made the mistake of using these composables inside `GoogleMap`, causing the crash encountered in https://github.com/googlemaps/android-maps-compose/issues/335. The idea is this change makes it less likely others would do the same.
Fixes #335
> chore: Improve Scalebar example in readme

- app/src/androidTest/java/com/google/maps/android/compose/MapInColumnTests.kt
This PR fixes an existing test (testPanMapUp_MapCameraChangesColumnDoesNotScroll) that was failing due to rounding.
---
Fixes #163  🦕
> fix: fixed failing test swipping on the map

- README.md
- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
- maps-compose/src/main/java/com/google/maps/android/compose/RememberComposeBitmapDescriptor.kt
- Create a Marker Composable that accepts a Composable content
- Update BasicMapActivity to show the Composable Marker
---
Fixes #41  🦕
> feat: customize Marker using Composable

- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/Clustering.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapApplier.kt
The following PR fixes an issue when multiple MarkerManagers are added (for instance, when we are adding multiple clusters), and only the last one is being triggered.
This has been solved by moving the execution of the invoke function within the reified `findInputCallback` function. The function will execute the callback click listener when we found a matching node or an input handler.
--
Fixes #294 and eventually #394
> fix: fixed issue when multiple marker managers have been added, for instance in multiple clustering

- .releaserc
Found that release flow [doesn't trigger a release](https://github.com/semantic-release/semantic-release/issues/2339) based on using `!` to indicate breaking changes in commit messages. Specify `conventionalcommit` message per [workaround](https://github.com/semantic-release/semantic-release/issues/2339#issuecomment-1451987883).
> chore: update semantic-release config

- .github/workflows/release.yml
This PR updates the JDK in the release workflow. This should fix the following failing action: https://github.com/googlemaps/android-maps-compose/actions/runs/6391132902
> chore: updating JDK in release workflow

- app/src/androidTest/java/com/google/maps/android/compose/MapInColumnTests.kt
Sometimes the map is recomposing, and two equal ones appear on the tree node.
This PR fixes the issue but selecting the first one.
Fixes #411 🦕
> fix: fixed test for MapInColumn

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- app/src/main/java/com/google/maps/android/compose/CustomControlsActivity.kt
- app/src/main/java/com/google/maps/android/compose/CustomLocationButtonActivity.kt
- app/src/main/java/com/google/maps/android/compose/LocationTrackingActivity.kt
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/java/com/google/maps/android/compose/StreetViewActivity.kt
- app/src/main/res/values/strings.xml
- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapClickListeners.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
The follogin PR adds customization options to the location button. We can add our own Composable as a custom Location button, or modify only the click behavior
Fixes #340 🦕
> feat: customizing the location button

- maps-compose/src/main/java/com/google/maps/android/compose/MapApplier.kt
This PR fixes the issue reported in #422 , to execute the callback in matching nodes after a click.
---
Fixes #422
> fix: fixed listener in matching node

- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/androidTest/java/com/google/maps/android/compose/StreetViewTests.kt
- app/src/androidTest/java/com/google/maps/android/compose/TestUtils.kt
This PR relaxes the timeout for our tests, so hopefully we will encounter less flaky failing tests.
---
Fixes #429 🦕
> chore: increased timeout times

- README.md
- app/src/main/java/com/google/maps/android/compose/StreetViewActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/streetview/StreetView.kt
This PR provides an in-app sample to manage invalid locations in Street View.
https://github.com/googlemaps/android-maps-compose/issues/265
---
Fixes #265 🦕
> chore: added StreetViewUtil sample

- app/src/main/java/com/google/maps/android/compose/CustomControlsActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
Update: this PR moves the custom location to the sample instead of managing it via the GoogleMap.
~~The following PR fixes an issue when a Modifier was set for GoogleMaps. This PR introduces a custom Modifier for the custom location row in the map, and adds this one only when a custom location has been added.~~
---
Fixes #427
> feat!: setting the custom location button via sample

- app/build.gradle
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
Switch from implementation to api dependency to expose the classes from maps-ktx in maps-compose.
---
Fixes #450 🦕
> fix: expose ktx classes to app-level modules

- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
Fixes inability to access all buttons in Main Activity on a small screen
Fixes #434
> fix: make example main activity scrollable to access all buttons on small screen

- app/src/main/java/com/google/maps/android/compose/MarkerClusteringActivity.kt
- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/Clustering.kt
Existing problems
- ClusterManager#setAlgorithm is not available.
- clusterContent and clusterItemContent are not used when clusterRenderer is specified.
As described in the Issue, we thought it would be less confusing for users to separate the low-level API and the high-level API.
Clustering Composable Function that takes a clusterManager as an argument, memberClusterRenderer and memberClusterManager are implemented and make public.
The existing Clustering Composable Function calls the low-level Clustering Composable Function.
-----
Fixes #420 🦕
> feat: Implemented so that ClusterManager#setAlgorithm can be use.

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
- app/src/main/res/values/strings.xml
This PR adds a recomposition sample, to showcase how to remove or add markers using a remember variable and recomposition.
https://github.com/googlemaps/android-maps-compose/assets/903097/098a6a95-4a24-45e0-b5e8-1acfa3b144ce
---
Fixes #442, #91, #403 🦕
> docs: added recomposition sample

- app/src/main/java/com/google/maps/android/compose/MarkerClusteringActivity.kt
The following PR showcases how to use a custom algorithm while clustering.
---
Fixes #380 🦕
> docs: demonstrate NonHierarchicalViewBasedAlgorithm for high-volume marker clustering

- README.md
- app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
This PR changes the recomposition sample to showcase a better usage of location within the MarkerState.
---
Fixes #448 🦕
> docs: improved recomposition sample

- .github/workflows/release.yml
This PR updates the setup-java GitHub Action to 4.2.1, eventually fixing an issue with the release flow where the artifact doesn't get published.
> chore: increase java-setup version

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/Clustering.kt
> fix: Fixed scope cancellation that leads to bug when invalidating composable doesn't invalidate cluster

- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
Fixed documentation broke in https://github.com/googlemaps/android-maps-compose/commit/450d842c38ca8ef9fb5938425408f57c3a793bb7
> chore: fixed documentation

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
> feat!: change GoogleMap() content parameter default to {} and make content non-nullable

- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
---
Fixes #<issue_number_goes_here> 🦕
> fix: documentation fix

- .github/workflows/instrumentation-test.yml
This PR updates the test coverage comment from JaCoCo, so it doesn't repeat after new commits are added to the PR.
> chore: updating JaCoCo comment

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapProperties.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUiSettings.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
> fix: make DefaultMapProperties, DefaultMapUiSettings, and NoPadding public

- app/build.gradle
- build.gradle
- gradle.properties
- gradle/libs.versions.toml
- maps-compose-utils/build.gradle
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
Kotlin 2.0.0 has been updated, and there are a few collateral changes. The K2 compiler is now activated by default.
- The Jetpack Compose compiler has moved to the Kotlin repository. This PR migrates to use the new plugin, as per [the migration instructions](https://android-developers.googleblog.com/2024/04/jetpack-compose-compiler-moving-to-kotlin-repository.html).
- `freeCompilerArgs` semantics migrated.
- buildconfig removed from gradle.properties, since this is scheduled to be removed in AGP 9.0.0.
- Some minor libraries updated.
- Kotlin version increased to 2.0.0
> chore: updated Kotlin to 2.0.0

- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
- maps-compose/src/main/java/com/google/maps/android/compose/RememberComposeBitmapDescriptor.kt
Fixes #518  🦕
By returning early in the case of invalid view width/height, we can avoid the IllegalArgumentException described in issue #518.
> fix: Return early in rememberComposeBitmapDescriptor for invalid view size

- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
- maps-compose/src/main/java/com/google/maps/android/compose/TileOverlay.kt
- maps-compose/src/main/java/com/google/maps/android/compose/streetview/StreetViewCameraPositionState.kt
The PR replaces public constructors on State objects with `invoke()` factory functions in public companion objects. `@StateFactoryMarker` can only be applied to functions, not constructors. The chosen constructor replacement approach minimizes the required refactoring impact on correct State object usages, requiring no refactoring in the vast majority of cases.
Fixes #506
> fix: leverage `@StateFactoryMarker` to flag State object creation without remember or similar mechanisms.

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
The following PR removes the default value for MapColorScheme, which conflicts with the tile mode.
---
Fixes #601 🦕
> chore: not adding by default the MapColorScheme

- .github/workflows/docs.yml
- .github/workflows/instrumentation-test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- app/build.gradle.kts
- gradle/libs.versions.toml
- maps-compose-utils/build.gradle.kts
- maps-compose-widgets/build.gradle.kts
- maps-compose/build.gradle.kts
This PR (depending on https://github.com/googlemaps/android-maps-ktx/pull/267) brings back Java 1.8 compatibility.
> chore: using Java 1.8

- .github/workflows/lint-report.yml
- app/build.gradle.kts
- app/src/main/java/com/google/maps/android/compose/markerexamples/AdvancedMarkersActivity.kt
- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- maps-compose-utils/build.gradle.kts
- maps-compose-widgets/build.gradle.kts
- maps-compose/build.gradle.kts
The following PR uploads the SARIF file from the Lint report to trace warnings.
> chore: added lint report

- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
Add `Composable` support for Marker inside `MakerInfoWindow`
---
Fixes #383  🦕
> feat: customize MarkerInfoWindow's Marker using Composable

- .github/workflows/release.yml
This PR updates a comment where the wrong Java version was being specified (17 when we are using 21)
> chore: specifying right version in Java version

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/Clustering.kt
> fix: Prevent Clustering with composable content from displaying default markers

- maps-compose/src/main/java/com/google/maps/android/compose/Circle.kt
Fixes #531 
Update the `Circle` function to use `Color.Black` as default, and a radius of `10`
> fix: update circle to be black and have a radius of 10

- maps-compose-utils/build.gradle.kts
- maps-compose-widgets/build.gradle.kts
- maps-compose/build.gradle.kts
- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
- maps-compose/src/main/java/com/google/maps/android/compose/streetview/StreetView.kt
The following PR upgrades the compileSdk version. It closes https://github.com/googlemaps/android-maps-compose/issues/649.
> feat: updated compileSdk version

- app/src/main/java/com/google/maps/android/compose/markerexamples/draggablemarkerscollectionwithpolygon/DraggableMarkersCollectionWithPolygonActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Polygon.kt
> fix: avoid Polygon crash on empty list of points

- .github/workflows/docs.yml
- .github/workflows/instrumentation-test.yml
- .github/workflows/lint-report.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
We realised that 6.4.2.and 6.4.3 were not published on Maven, despite the logs looking good. The only change in the configuration that could have potentially caused this is this update, since all the other changes were not related to the configuration files.
> fix: potential fix for publication issues

- README.md
Fix broken links to Google Maps Platform Technical Support Services Guidelines and SLA introduced in commit 0ecc362.
> chore: Fix broken links to Google Maps Platform Technical Support Services Guidelines and SLA.

- README.md
I skipped the "create an issue" step due to this being a very trivial documentation fix – do let me know if you'd still need one though. 🙂
> docs: Fix broken link to maps-app project in README

- .github/workflows/automerge-docs.yml
This PR removes the Dependabot automated merge flow (which is problematic, as it could potentially merge a compiling PR that introduces runtime errors). Instead, we now have a new action that merges contributions from googlemaps-bot, specifically documentation PRs (unless AI turns against humankind and googlemaps-bot starts creating other types of PRs, but since AGI is expected to arrive on average by 2040 [according to this article](https://www.livescience.com/technology/artificial-intelligence/agi-could-now-arrive-as-early-as-2026-but-not-all-scientists-agree), this is not a concern for now).
It seems also that googlemaps is really an app and not a bot, according to this image, so checking the author like this should work, instead of the former approach for dependabot.
> chore: automerge docs PRs

- .github/workflows/lint-report.yml
This PR modifies the flow to avoid having Lint running on each commit to push - we are already doing it on the PR, and the commit to main does not need it.
> chore: not run lint on push onto main

- maps-compose/src/main/java/com/google/maps/android/compose/RememberComposeBitmapDescriptor.kt
This PR fixes an issue that was not properly done on the MarkerComposable, and that was probably introducing some performance issues (not all the problems we had were attributable to it, but certainly a percentage of them).
The main issue is that we have been measuring the view after drawing it. The procedure should have been [measure and layout, then draw](https://developer.android.com/guide/topics/ui/how-android-draws).
The `fakeCanvas` was also unnecessary, since `applyCanvas` creates one.
So overall, this should improve performance a bit.
> fix: fixed issue on MarkerComposable

- .github/workflows/instrumentation-test.yml
- .github/workflows/test.yml
This PR fixes the path for the Lint and Screenshot report, which was pointing out to the previous folder structure (`app` instead of `maps-app`)
> chore: modified path for the Test report

- README.md
- maps-app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- maps-app/src/main/java/com/google/maps/android/compose/AccessibilityActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/MapInColumnActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/markerexamples/AdvancedMarkersActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/markerexamples/MarkerClusteringActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/markerexamples/markerdragevents/MarkerDragEventsActivity.kt
- maps-app/src/main/java/com/google/maps/android/compose/markerexamples/syncingdraggablemarkerwithdatamodel/SyncingDraggableMarkerWithDataModelActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
`rememberMarkerState` has been deprecated in the commit https://github.com/googlemaps/android-maps-compose/commit/0d6f023767f8ef8ede5950ecbb66f3b0c1f0e8a2.
We should replace `rememberMarkerState` with `rememberUpdatedMarkerState`, so users can see the best practices in the samples.
> chore: remove rememberMarkerState from samples

- gradle/libs.versions.toml
This PR updates some of the dependencies, most notably [Kotlin to 2.2.0 ](https://github.com/JetBrains/kotlin/releases/tag/v2.2.0)There does not seem to be any required change in the code.
Dokka has been updated to 2.0.0. We do not require a migration in our Convention plugin, and `./gradlew dokkaHtmlMultiModule` works to deploy the documentation.
There is a non-resolved bug with Compose that breaks the Scale Bar, so the Compose BoM is not updated.
This PR will not trigger a release, to pack it with some other features.
> chore: libraries updated

- build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt
The following PR adds the org information to the vanniktech Maven plugin.
> chore: added org to Vanniktech Maven Plugin

- README.md
- maps-app/src/main/java/com/google/maps/android/compose/LocationTrackingActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/CameraPositionState.kt
After the [version 6.7.2](https://github.com/googlemaps/android-maps-compose/releases/tag/v6.7.2) was introduced, it become obvious that [for users trying to set the camera state](https://github.com/googlemaps/android-maps-compose/issues/740) before the map was loaded this could lead to a crash.
This is a small PR clarifying on the documentation how to modify the camera state in combination with the `onMapLoaded` callback.
> docs: improved documentation for camera state

- .releaserc
This PR fixes the issue with the release flow.
We need to exclude the screenshot testing tasks from the build process, until the screenshot library offers support for the latest Gradle version (or we migrate to Gradle 9)
> build: updated releaserc file

- .github/workflows/release.yml
This PR upgrades the node version.
The latest semantic-versioning version fails. There is a new `actions/setup-node` version, checking if this fixes it.
> build: upgrade node version
