- README.md
Just fix incorrect property name on README
Fixes #8🦕
> docs: fix incorrect property name on README

- app/build.gradle
- build.gradle
- maps-compose/build.gradle
- maps-compose/src/main/java/com/google/maps/android/compose/MapProperties.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUiSettings.kt
* Add Jacoco
* Remove unused dependencies (Fixes #6, #7)
* Use specific version (Fixes #4)
* Document class vs. data class (#5)
> chore: Add jacoco and remove unused dependencies.

- CONTRIBUTING.md
- README.md
Add reference to https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md
> docs: Add Compose API guidelines

- .github/autoapproval.yml
- .github/blunderbuss.yml
- .github/dependabot.yml
- .github/stale.yml
- app/src/androidTest/java/com/google/maps/android/compose/GoogleMapViewTests.kt
- maps-compose/src/main/java/com/google/maps/android/compose/ComposeInfoWindowAdapter.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapClickListeners.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapProperties.kt
- maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt
Add license to files missing headers.
> chore: Add license headers.

- app/build.gradle
> chore: Remove core-ktx from demo app.

- .github/blunderbuss.yml
> chore: Update blunderbuss.yml.

- app/build.gradle
Add the Maps SDK declaration to the `maps_compose_dependency` region tag and also remove trailing "silent" from `END_EXCLUDE`
> chore: Edit maps_compose_dependency region tag.

- app/build.gradle
This is needed following PR https://github.com/googlemaps/android-maps-compose/pull/109, otherwise users will get a crash when tapping the "Toggle Map" button in the demo app (caused by https://github.com/googlemaps/android-maps-compose/issues/106, which is fixed in v2.1.1 release).
---
> chore: Bump library dependency in app

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
Reverts googlemaps/android-maps-compose#188
> Revert "fix: Prevent a memory leak on AndroidView which may not call ON_DESTROY"

- app/build.gradle
- app/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- maps-compose-widgets/build.gradle
- maps-compose-widgets/src/main/AndroidManifest.xml
- maps-compose/build.gradle
- maps-compose/src/main/AndroidManifest.xml
Maintenance. Hopefully will bring improvements to Managed Devices so we can use those for connected tests.
> chore: Upgrade Gradle to 7.5.1, AGP to 7.3.1

- maps-compose/src/main/java/com/google/maps/android/compose/TileOverlay.kt
I think it would be more Compose-like to observe created Tiles as a state, rather than imperatively invalidate them. However, the underlying Maps API doesn't seem to play nice with that, so this is better than nothing.
Fixes #197 🦕
> feat: Expose function for clearing tile overlay tiles

- maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt
In Clustering, a job is launched to rerender icons when they're invalidated, but this job is never canceled (until the Clustering is gone). This fixes it by tying it to the `RenderHandle`'s lifecycle.
May improve performance after changing zoom level or cluster items.
> fix: Fix clustering render leak for items that are removed

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
The following PR creates a Factory for GoogleMap, and it facilitates its usage on tests.
---
Fixes #342 🦕
> feat: added Factory for Map

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
This PR adds some documentation for the `GoogleMapFactory`.
---
Fixes #362
> docs: added documentation for the GoogleMapFactory

- README.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/google/maps/android/compose/AdvancedMarkersActivity.kt
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/java/com/google/maps/android/compose/MarkerClusteringActivity.kt
- app/src/main/res/values/strings.xml
- gradle/libs.versions.toml
- maps-compose-utils/build.gradle
- maps-compose-widgets/build.gradle
- maps-compose/build.gradle
- maps-compose/src/main/java/com/google/maps/android/compose/Marker.kt
The following PR adds support for Advanced Markers.
---
Fixes #439  🦕
> feat: added support for Advanced Markers

- app/src/main/java/com/google/maps/android/compose/CustomControlsActivity.kt
The following PR adds custom zoom controls.
---
Fixes #339 🦕
> docs: added custom zoom controls

- maps-compose/src/main/java/com/google/maps/android/compose/GoogleMap.kt
> fix: properly support updating GoogleMap() contentDescription parameter

- .github/workflows/docs.yml
- .github/workflows/instrumentation-test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
The following PR updates and revamps the GitHub Action dependencies.
> chore(deps): updated and revamped GA dependencies

- README.md
- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- maps-compose/src/main/java/com/google/maps/android/compose/Polyline.kt
Fixes #307 🦕
There's a [similar PR](https://github.com/googlemaps/android-maps-compose/pull/308) that was proposed some time ago. Unfortunately, the author has not responded or continued working on it.
Therefore, created a similar PR that takes into account the latest changes from the comments. 
---
> feat: Add StyleSpans support for Polylines

- app/src/main/java/com/google/maps/android/compose/ScaleBarActivity.kt
- maps-compose-widgets/src/main/java/com/google/maps/android/compose/widgets/ScaleBar.kt
> fix: metric ScaleBar text not rendering correctly (#527)

- .releaserc
The current PR fixes the release step, to properly modify the version in a KTX file.
> fix: fix release step

- .github/workflows/release.yml
- .releaserc
- build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt
- gradle.properties
This PR changes the authentication credentials to start using the new Sonatype tokens.
> chore: update Sonatype token

- app/build.gradle.kts
- gradle/libs.versions.toml
- maps-compose-utils/build.gradle.kts
- maps-compose-widgets/build.gradle.kts
- maps-compose/build.gradle.kts
This PR introduces a direct dependency on the Kotlin Coroutines library, as methods from this library are used in code
> chore: added kotlin-coroutines dependency

- gradle/libs.versions.toml
The following PR fixes a problem with the TOML file.
---
Fixes #605 🦕
> fix: fix TOML version

- app/src/main/java/com/google/maps/android/compose/AccessibilityActivity.kt
- app/src/main/java/com/google/maps/android/compose/BasicMapActivity.kt
- app/src/main/java/com/google/maps/android/compose/CustomControlsActivity.kt
- app/src/main/java/com/google/maps/android/compose/LocationTrackingActivity.kt
- app/src/main/java/com/google/maps/android/compose/MainActivity.kt
- app/src/main/java/com/google/maps/android/compose/MapInColumnActivity.kt
- app/src/main/java/com/google/maps/android/compose/MapsInLazyColumnActivity.kt
- app/src/main/java/com/google/maps/android/compose/RecompositionActivity.kt
- app/src/main/java/com/google/maps/android/compose/ScaleBarActivity.kt
- app/src/main/java/com/google/maps/android/compose/StreetViewActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/AdvancedMarkersActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/MarkerClusteringActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/draggablemarkerscollectionwithpolygon/DraggableMarkersCollectionWithPolygonActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/markerdragevents/MarkerDragEventsActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/markerscollection/MarkersCollectionActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/syncingdraggablemarkerwithdatamodel/SyncingDraggableMarkerWithDataModelActivity.kt
- app/src/main/java/com/google/maps/android/compose/markerexamples/updatingnodragmarkerwithdatamodel/UpdatingNoDragMarkerWithDataModelActivity.kt
https://developer.android.com/develop/ui/views/layout/edge-to-edge
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/ed1dcfb9-fe81-43e8-9c8b-fb4f569466db) | ![after](https://github.com/user-attachments/assets/cd3b68f5-3b03-44a9-819f-220c70a95bdd) |
---
> fix: enable edge-to-edge in sample

- README.md
Small PR - Commit 98fbd396b2f90decaafad28673d3f2b7cc6b10c8 moved files from `app/` to `maps-app/`. This PR adjusts sources to changes.
> docs: fix examples sources
